### ISSUE TITLE
Arrays with defaults should not be nullable

### ISSUE THREAD

**Issue by kynx** [kynx/mezzio-openapi-generator#1]
The following property definition:
```
        componentTypes:
          type: array
          items:
              type: string
          default:
            - resource
            - waste
```
is converted to:
```
        private readonly array|null $componentTypes,
```

It should be:
```
        private readonly array $componentTypes = ['resource', 'waste'],
```
